config/routes.rb
Rails.application.routes.draw do

  resources :comments

  resources :wine_classes

  resources :weeks

  resources :wines

  devise_for :users
  root :to => "static_pages#home"

  StaticPagesController.action_methods.each do |action|
    get "/#{action}", to: "static_pages##{action}", as: "#{action}"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :ldap_authenticatable, :rememberable, :trackable
end

app/models/week.rb
class Week < ActiveRecord::Base
  has_many :wine
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :week
end

app/models/wine_class.rb
class WineClass < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from DeviseLdapAuthenticatable::LdapException do |exception|
    render :text => exception, :status => 500
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    flash[:notice] = 'Comment was successfully created.' if @comment.save
    redirect_to request.referrer
  end

  def update
    flash[:notice] = 'Comment was successfully updated.' if @comment.update(comment_params)
    redirect_to request.referrer
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:wine_id, :user_id, :see, :smell, :swirl, :sip, :swallow, :savor)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :set_week, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @weeks = Week.all.page(params[:page]).per_page(1)
    @comments = Comment.all
    respond_with(@weeks)
  end

  def show
    respond_with(@week)
  end

  def new
    @week = Week.new
    respond_with(@week)
  end

  def edit
  end

  def create
    @week = Week.new(week_params)
    flash[:notice] = 'Week was successfully created.' if @week.save
    respond_with(@week)
  end

  def update
    flash[:notice] = 'Week was successfully updated.' if @week.update(week_params)
    respond_with(@week)
  end

  def destroy
    @week.destroy
    respond_with(@week)
  end

  private
    def set_week
      @week = Week.find(params[:id])
    end

    def week_params
      params.require(:week).permit(:week_number, :class_id, :wine_id)
    end
end

app/controllers/wine_classes_controller.rb
class WineClassesController < ApplicationController
  before_action :set_wine_class, only: [:show, :edit, :update, :destroy]

  def index
    @wine_classes = WineClass.all
    respond_with(@wine_classes)
  end

  def show
    respond_with(@wine_class)
  end

  def new
    @wine_class = WineClass.new
    respond_with(@wine_class)
  end

  def edit
  end

  def create
    @wine_class = WineClass.new(wine_class_params)
    flash[:notice] = 'WineClass was successfully created.' if @wine_class.save
    respond_with(@wine_class)
  end

  def update
    flash[:notice] = 'WineClass was successfully updated.' if @wine_class.update(wine_class_params)
    respond_with(@wine_class)
  end

  def destroy
    @wine_class.destroy
    respond_with(@wine_class)
  end

  private
    def set_wine_class
      @wine_class = WineClass.find(params[:id])
    end

    def wine_class_params
      params.require(:wine_class).permit(:name, :meeting_time)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @wines = Wine.all
    respond_with(@wines)
  end

  def show
    respond_with(@wines)
  end

  def new
    @wine = Wine.new
    respond_with(@wines)
  end

  def edit
  end

  def create
    @wine = Wine.new(wine_params)
    flash[:notice] = 'Wine was successfully created.' if @wine.save
    respond_with(@wine)
  end

  def update
    flash[:notice] = 'Wine was successfully updated.' if @wine.update(wine_params)
    respond_with(@wine)
  end

  def destroy
    @wine.destroy
    respond_with(@wines)
  end

  private
    def set_wine
      @wine = Wine.find(params[:id])
    end

    def wine_params
      params.require(:wine).permit(:producer, :grape, :country, :region, :vintage, :price, :alcohol_percentage, :week_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/helpers/wine_classes_helper.rb
module WineClassesHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wine_id %><br>
    <%= f.number_field :wine_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :see %><br>
    <%= f.text_area :see %>
  </div>
  <div class="field">
    <%= f.label :smell %><br>
    <%= f.text_area :smell %>
  </div>
  <div class="field">
    <%= f.label :swirl %><br>
    <%= f.text_area :swirl %>
  </div>
  <div class="field">
    <%= f.label :sip %><br>
    <%= f.text_area :sip %>
  </div>
  <div class="field">
    <%= f.label :swallow %><br>
    <%= f.text_area :swallow %>
  </div>
  <div class="field">
    <%= f.label :savor %><br>
    <%= f.text_area :savor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Wine</th>
      <th>User</th>
      <th>See</th>
      <th>Smell</th>
      <th>Swirl</th>
      <th>Sip</th>
      <th>Swallow</th>
      <th>Savor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.wine_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.see %></td>
        <td><%= comment.smell %></td>
        <td><%= comment.swirl %></td>
        <td><%= comment.sip %></td>
        <td><%= comment.swallow %></td>
        <td><%= comment.savor %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine:</strong>
  <%= @comment.wine_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>See:</strong>
  <%= @comment.see %>
</p>

<p>
  <strong>Smell:</strong>
  <%= @comment.smell %>
</p>

<p>
  <strong>Swirl:</strong>
  <%= @comment.swirl %>
</p>

<p>
  <strong>Sip:</strong>
  <%= @comment.sip %>
</p>

<p>
  <strong>Swallow:</strong>
  <%= @comment.swallow %>
</p>

<p>
  <strong>Savor:</strong>
  <%= @comment.savor %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<!-- Site footer -->
<div class="bottom">
  <div class="container">
    <div class="col-md-4">
      <h3><a href="https://siscalendar.rit.edu/sisCalendar">Your Schedule</a></h3>
      <p>Click the link above for when and where your class is</p>
      <p>You can also find your finals schedule here as well</p>
    </div>
    <div class="col-md-4">
      <h3><a href="http://www.rit.edu/cast/htm/faculty/?last-name=h">Lorraine Hems</a></h3>
      <p>To Contact the professor</p>
    </div>
    <div class="col-md-4">
      <h3><a href="https://www.rit.edu/cast/htm/undergraduate/ihsm/"> More Classes you can take</a></h3>
      <p>Click on Semester Curriculum</p>
      <p>Scroll down through these classes</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- Site header and navigation -->
<header class="top" role="header">
  <div class="container">
    <a href="/" class="navbar-brand pull-left">
      <img style="width: auto" height="150%" src="http://3.bp.blogspot.com/-2lFCgSlo-ck/T5KWu64r6uI/AAAAAAAAEgY/7VqeaMcOkwg/s1600/wine+glass.PNG">
      Wines of the World
    </a>
    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="glyphicon glyphicon-align-justify"></span>
    </button>
    <nav class="navbar-collapse collapse" role="navigation">
      <ul class="navbar-nav nav pull-right top-links">
        <% if current_user == nil %>
             <li><a class="top-links" href="#home">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li>
          <div class="form-inline" role="form" style="padding-bottom: 1rem; padding-top: .8rem;">
            <%= form_for(:user, :url => session_path(:user)) do |f| %>
              <div class="form-group">
                <%= f.text_field :login, :placeholder => "RIT DCE", :tabindex => 1, :class => "form-control" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, :placeholder => "Password", :tabindex => 2, :class => "form-control" %>
              </div>
              <div class="form-group">
                <%= f.submit 'Sign in', :tabindex => 3, :class => "form-control" %>
              </div>
            <% end %>
          </div>
        <% else %>
            <li><%= link_to "Wines", wines_path, class: "nav-item" %></li>
            <li><%= link_to "Weeks", weeks_path, class: "nav-item" %></li>
            <li><%= link_to "Sign-out", destroy_user_session_path, :method => :delete, class: "nav-item" %></li>
        <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WinesOfTheWorld</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/header' %>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
<div id="push"></div>
<%= render 'layouts/footer' %>
</html>

app/views/static_pages/home.html.erb
<h1 style="text-align: center"> Come Enjoy The Wine! </h1>
<body>
  <div class="container">
    <div class="row-fluid">
      <section id="home">
        <div class="card">
          <div>
            <div style="float: left; width: 35%">
              <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS32hcBwKZMonLanMpvQwkC0HdCqXjpqrtJiRKauRC5pQyR1dVa0g">
            </div>
            <div style="float: right; width: 65%">
              <h2> Welcome to wines of the world! This class is focused on us learning about wine history, learning what
                helps flavor these delicious wines, where in the world we can find our favorite wines, and an opportunity
                to try and discover new wines.
              </h2>
            </div>
            <div style="float: none; clear:both;"> </div>
            <hr>
            <div style="float: right; width: 50%">
              <img style="width: 100%;" src="http://i2.cdn.turner.com/cnn/dam/assets/121001025907-row-of-wine-bottles-story-top.jpg">
            </div>
            <div style="float: left; width: 50%">
              <h2> This class is focused on learning a little more each week and as time progresses. Every week we will
                be trying 5 or 6 different wines from both the old world and the New World.
              </h2>
            </div>
            <div style="float: none; clear:both;"> </div>
            <hr>
          </div>
        </div>
      </section>
      <br>
      <section id="about">
        <div class="card">
          <div style="float: left; width: 35%">
            <img style="width: 100%" src="http://www.gannett-cdn.com/-mm-/43e9732f1e2c7d9d9f0a4359453c4b17361b6f62/c=88-0-2743-3540&r=537&c=0-0-534-712/local/-/media/Rochester/2014/02/24/rocflavorslorrainehemsb080912.jpg">
          </div>
          <div style="float: right; width: 65%">
            <h1>Your Professor: Lorraine Hems </h1>
            <h2>Lorraine Hems, is a world renown <a style="font-size: 3rem; color: deepskyblue" href="http://www.rit.edu/news/story.php?id=49160">wine expert</a>
              who has had a number of different stories, experiences and tastes to share with you as you begin your
              adventure into the complex world of wines.
            </h2>
          </div>
          <div style="float: none; clear:both;"> </div>
          <hr>
        </div>
      </section>
      <br>
      <section id="contact">
        <div class="card">
          <div style="float: left; width: 35%">
            <img style="width: 100%" src="http://peachlandradio.com/wp-content/uploads/2014/01/contact.jpg">
          </div>
          <div style="float: right; width: 65%">
            <h1>Lorraine Hems </h1>
            <ul>
              <li><h2>Phone Number: (585) 475-6487</h2></li>
              <li><h2>Email: lehism@rit.edu</h2></li>
              <li><h2>Office Location: 4260 Eastman</h2></li>
            </ul>
          </div>
          <div style="float: none; clear:both;"> </div>
          <hr>
        </div>
      </section>
      </div>
    </div>
</body>

app/views/weeks/_form.html.erb
<div class="card">
  <%= form_for(@week) do |f| %>
    <% if @week.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@week.errors.count, "error") %> prohibited this week from being saved:</h2>

        <ul>
        <% @week.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field" align="center">
      <%= f.label :week_number %><br>
      <%= f.number_field :week_number %>
    </div>
    <div class="actions" align="center">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/weeks/edit.html.erb
<h1>Editing week</h1>

<%= render 'form' %>

<%= link_to 'Show', @week %> |
<%= link_to 'Back', weeks_path %>

app/views/weeks/index.html.erb
<h1>Week</h1>
<h2 style="margin: 0 auto; float: left"><%= will_paginate @weeks%></h2>

<div style="clear: both"></div>
<div class="card">
  <% @weeks.each do |week| %>
      <% week.wine.each do |wine| %>

          <!--<h1>Week <%= week.week_number %></h1>-->
  <div style="width: 50%">
    <div style="float: left">
      <h3>Wine Producer: <b><%= wine.producer %></b></h3>
    </div>
    <div style="float: right">
      <h3>Grape(s): <b><%= wine.grape %></b></h3>
    </div>
    <div style="clear: both"></div>
    <div style="float: left">
      <h3>Country: <b><%= wine.country %></b></h3></div>
    <div style="float: right">
      <h3>Regison: <b><%= wine.region %></b></h3>
    </div>
    <div style="clear: both"></div>
    <div style="float: left">
      <h3>Year: <b><%= wine.vintage %></b></h3></div>
    <div style="float: right">
      <h3>Price: <b><%= wine.price %></b></h3>
    </div>
    <div style="clear: both"></div>
    <div style="float: left">
      <h3>Alcohol %: <b><%= wine.alcohol_percentage %></b></h3>
    </div>
  </div>
  <div style="clear: both"></div>
  <div style="clear: both"></div>
  <% @comments.each do |comment| %>
      <% if comment.wine_id == wine.id and comment.user_id ==current_user.id %>
          <% @comment = comment %>
      <% end %>
  <% end %>
  <% @comment = Comment.new if @comment.nil? %>
  <%= form_for(@comment) do |f| %>
      <div style="float: left">
        <%= f.hidden_field :wine_id, :value => wine.id %>
      </div>
      <div style="float: left">
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>
      <div style="float: left">
        <%= f.label :see %><br>
        <%= f.text_area :see %>
      </div>
      <div style="float: left">
        <%= f.label :smell %><br>
        <%= f.text_area :smell %>
      </div>
      <div style="float: left">
        <%= f.label :swirl %><br>
        <%= f.text_area :swirl %>
      </div>
      <div style="float: left">
        <%= f.label :sip %><br>
        <%= f.text_area :sip %>
      </div>
      <div style="float: left">
        <%= f.label :swallow %><br>
        <%= f.text_area :swallow %>
      </div>
      <div style="float: left">
        <%= f.label :savor %><br>
        <%= f.text_area :savor %>
      </div>
      <div style="float: left">
        <%= f.submit %>
      </div>

      <div style="clear: both"></div>
      <br>
      <hr style=" display: block; height: 1px;
              border: 0; border-top: 1px solid #ccc;
              margin: 1em 0; padding: 0; ">
      <br>
  <% end %>
  <% @comment = nil %>
          <% end %>
  <% end %>
</div>

<!--<%= link_to 'New Week', new_week_path %>-->

app/views/weeks/new.html.erb
<h1 align="center">New week</h1>

<%= render 'form' %>

<%= link_to 'Back', weeks_path %>

app/views/weeks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Week number:</strong>
  <%= @week.week_number %>
</p>

<p>
  <strong>Class:</strong>
  <%= @week.class_id %>
</p>

<p>
  <strong>Wine:</strong>
  <%= @week.wine_id %>
</p>

<%= link_to 'Edit', edit_week_path(@week) %> |
<%= link_to 'Back', weeks_path %>

app/views/wine_classes/_form.html.erb
<%= form_for(@wine_class) do |f| %>
  <% if @wine_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine_class.errors.count, "error") %> prohibited this wine_class from being saved:</h2>

      <ul>
      <% @wine_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :meeting_time %><br>
    <%= f.date_select :meeting_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wine_classes/edit.html.erb
<h1>Editing wine_class</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine_class %> |
<%= link_to 'Back', wine_classes_path %>

app/views/wine_classes/index.html.erb
<h1>Listing wine_classes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Meeting time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wine_classes.each do |wine_class| %>
      <tr>
        <td><%= wine_class.name %></td>
        <td><%= wine_class.meeting_time %></td>
        <td><%= link_to 'Show', wine_class %></td>
        <td><%= link_to 'Edit', edit_wine_class_path(wine_class) %></td>
        <td><%= link_to 'Destroy', wine_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine class', new_wine_class_path %>

app/views/wine_classes/new.html.erb
<h1>New wine_class</h1>

<%= render 'form' %>

<%= link_to 'Back', wine_classes_path %>

app/views/wine_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine_class.name %>
</p>

<p>
  <strong>Meeting time:</strong>
  <%= @wine_class.meeting_time %>
</p>

<%= link_to 'Edit', edit_wine_class_path(@wine_class) %> |
<%= link_to 'Back', wine_classes_path %>

app/views/wines/_form.html.erb
<div class="card">
<%= form_for(@wine) do |f| %>
  <% if @wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% @wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div class="field" style="float: left; width: 50%">
      <%= f.label :producer %><br>
      <%= f.text_field :producer %>
    </div>
    <div class="field"style="float: right; width: 50%">
      <%= f.label :grape %><br>
      <%= f.text_field :grape %>
    </div>
  </div>
  <div>
    <div class="field" style="float: left; width: 50%">
      <%= f.label :country %><br>
      <%= f.text_field :country %>
    </div>
    <div class="field" style="float: right; width: 50%">
      <%= f.label :region %><br>
      <%= f.text_field :region %>
    </div>
  </div>
  <div>
    <div class="field" style="float: left; width: 50%">
      <%= f.label :vintage %><br>
      <%= f.text_field :vintage %>
    </div>
    <div class="field" style="float: right; width: 50%">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
  </div>
  <div>
    <div class="field" style="float: left; width: 50%">
      <%= f.label :alcohol_percentage %><br>
      <%= f.text_field :alcohol_percentage %>
    </div>
    <div class="field" style="float: right; width: 50%">
      <%= f.label :week_id %><br>
      <%= f.number_field :week_id %>
    </div>
    <div class="actions" align="center">
      <br>
      <%= f.submit %>
    </div>
  </div>
  <div style="float: none; clear:both;"> </div>
<% end %>
</div>

app/views/wines/edit.html.erb
<h1>Editing wine</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<h1>Listing wines</h1>

<table>
  <thead>
    <tr>
      <th>Producer</th>
      <th>Grape</th>
      <th>Country</th>
      <th>Region</th>
      <th>Vintage</th>
      <th>Price</th>
      <th>Alcohol percentage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.producer %></td>
        <td><%= wine.grape %></td>
        <td><%= wine.country %></td>
        <td><%= wine.region %></td>
        <td><%= wine.vintage %></td>
        <td><%= wine.price %></td>
        <td><%= wine.alcohol_percentage %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1 style="text-align: center">New Wine</h1>

<%= render 'form' %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
          <div style="width: 50%">
            <div style="float: left">
              <h3>Wine Producer: <b><%= @wine.producer %></b></h3>
            </div>
            <div style="float: right">
              <h3>Grape(s): <b><%= @wine.grape %></b></h3>
            </div>
            <div style="clear: both"></div>
            <div style="float: left">
              <h3>Country: <b><%= @wine.country %></b></h3></div>
            <div style="float: right">
              <h3>Regison: <b><%= @wine.region %></b></h3>
            </div>
            <div style="clear: both"></div>
            <div style="float: left">
              <h3>Year: <b><%= @wine.vintage %></b></h3></div>
            <div style="float: right">
              <h3>Price: <b><%= @wine.price %></b></h3>
            </div>
            <div style="clear: both"></div>
            <div style="float: left">
              <h3>Alcohol %: <b><%= @wine.alcohol_percentage %></b></h3>
            </div>
          </div>
          <div style="clear: both"></div>
          </div>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>